CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    discord_id VARCHAR(120),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key VARCHAR(80) NOT NULL UNIQUE,
    purchase_reference VARCHAR(120) NOT NULL UNIQUE,
    buyer_name VARCHAR(120) NOT NULL,
    buyer_email VARCHAR(190) NOT NULL,
    source VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    discord_id VARCHAR(120),
    fivem_server_id VARCHAR(120),
    product_id BIGINT NOT NULL,
    owner_id BIGINT,
    last_validated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_license_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_license_owner FOREIGN KEY (owner_id) REFERENCES app_users (id)
);

CREATE TABLE license_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id BIGINT NOT NULL,
    action VARCHAR(80) NOT NULL,
    message VARCHAR(500) NOT NULL,
    metadata_json VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_license FOREIGN KEY (license_id) REFERENCES licenses (id)
);

