ALTER TABLE app_users ADD COLUMN oauth_provider VARCHAR(40);
ALTER TABLE app_users ADD COLUMN oauth_subject VARCHAR(190);

CREATE UNIQUE INDEX uq_app_users_oauth_identity ON app_users (oauth_provider, oauth_subject);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(120) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE INDEX idx_password_reset_user_id ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_expires_at ON password_reset_tokens (expires_at);

